"""add 'is_used' for images

Revision ID: 22a728502c4b
Revises: b1eb0f49a95b
Create Date: 2026-04-19 12:59:39.431692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a728502c4b'
down_revision: Union[str, Sequence[str], None] = 'b1eb0f49a95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('is_used', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_images', 'is_used')
    # ### end Alembic commands ###
