"""fix post_images schea

Revision ID: b1eb0f49a95b
Revises: 2f569d835e91
Create Date: 2026-04-19 12:40:53.012371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1eb0f49a95b'
down_revision: Union[str, Sequence[str], None] = '2f569d835e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('post_images_sort_order_fkey'), 'post_images', type_='foreignkey')
    op.create_foreign_key(None, 'post_images', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_images', type_='foreignkey')
    op.create_foreign_key(op.f('post_images_sort_order_fkey'), 'post_images', 'posts', ['sort_order'], ['id'], ondelete='CASCADE')
    op.drop_column('post_images', 'post_id')
    # ### end Alembic commands ###
